export default {
    "angel": {
        "name": "Angel",
        "abrv": "Ang",
        "total": 18,
        "power": 6,
        "skill": 4,
        "requires": [],
        "native": [],
        "fly": true,
        "range": false
    },
    "archangel": {
        "name": "Archangel",
        "abrv": "Arc",
        "total": 6,
        "power": 9,
        "skill": 4,
        "requires": [],
        "native": [],
        "fly": true,
        "range": true
    },
    "behemoth": {
        "name": "Behemoth",
        "abrv": "Beh",
        "total": 18,
        "power": 8,
        "skill": 3,
        "requires": [{ "cyclops": 3 }],
        "native": ["jungle"],
        "fly": false,
        "range": false
    },
    "centaur": {
        "name": "Centaur",
        "abrv": "Cen",
        "total": 25,
        "power": 3,
        "skill": 4,
        "requires": [],
        "native": ["tower", "plains", "woods"],
        "fly": false,
        "range": false
    },
    "colossus": {
        "name": "Colossus",
        "abrv": "Col",
        "total": 10,
        "power": 10,
        "skill": 4,
        "requires": [{ "giant": 2, "dragon": 2 }],
        "native": ["tundra", "mountains"],
        "fly": false,
        "range": false
    },
    "cyclops": {
        "name": "Cyclops",
        "abrv": "Cyc",
        "total": 28,
        "power": 9,
        "skill": 2,
        "requires": [{ "gargoyle": 2 }],
        "native": ["brush", "jungle"],
        "fly": false,
        "range": false
    },
    "dragon": {
        "name": "Dragon",
        "abrv": "Dra",
        "total": 18,
        "power": 9,
        "skill": 3,
        "requires": [{ "minotaur": 2 }],
        "native": ["mountains"],
        "fly": true,
        "range": true
    },
    "gargoyle": {
        "name": "Gargoyle",
        "abrv": "Gar",
        "total": 21,
        "power": 4,
        "skill": 3,
        "requires": [],
        "native": ["tower", "brush", "jungle"],
        "fly": true,
        "range": false
    },
    "giant": {
        "name": "Giant",
        "abrv": "Gia",
        "total": 18,
        "power": 7,
        "skill": 4,
        "requires": [{ "warbear": 2 }],
        "native": ["tundra"],
        "fly": false,
        "range": true
    },
    "gorgon": {
        "name": "Gorgon",
        "abrv": "Gor",
        "total": 25,
        "power": 6,
        "skill": 3,
        "requires": [{ "cyclops": 2 }],
        "native": ["brush"],
        "fly": true,
        "range": true
    },
    "griffon": {
        "name": "Griffon",
        "abrv": "Gri",
        "total": 18,
        "power": 5,
        "skill": 4,
        "requires": [{ "lion": 3 }],
        "native": ["desert"],
        "fly": true,
        "range": false
    },
    "guardian": {
        "name": "Guardian",
        "total": 6,
        "power": 12,
        "skill": 2,
        "requires": [{ "centaur": 3 }, { "gargoyle": 3 }, { "ogre": 3 }],
        "native": ["tower"],
        "fly": true,
        "range": false
    },
    "hydra": {
        "name": "Hydra",
        "abrv": "Hyd",
        "total": 10,
        "power": 10,
        "skill": 3,
        "requires": [{ "griffon": 2 }, { "wyvern": 2 }],
        "native": ["desert", "swamp"],
        "fly": false,
        "range": true
    },
    "lion": {
        "name": "Lion",
        "abrv": "Lio",
        "total": 28,
        "power": 5,
        "skill": 3,
        "requires": [{ "centaur": 2 }],
        "native": ["plains", "desert", "mountains"],
        "fly": false,
        "range": false
    },
    "minotaur": {
        "name": "Minotaur",
        "abrv": "Min",
        "total": 21,
        "power": 4,
        "skill": 4,
        "requires": [{ "ogre": 3 }],
        "native": ["hills", "mountains"],
        "fly": false,
        "range": true
    },
    "ogre": {
        "name": "Ogre",
        "abrv": "Ogr",
        "total": 25,
        "power": 6,
        "skill": 2,
        "requires": [],
        "native": ["tower", "marsh", "hills"],
        "fly": false,
        "range": false
    },
    "ranger": {
        "name": "Ranger",
        "abrv": "Ran",
        "total": 28,
        "power": 4,
        "skill": 4,
        "requires": [{ "troll": 2 }, { "lion": 2 }],
        "native": ["plains", "marsh"],
        "fly": true,
        "range": true
    },
    "serpent": {
        "name": "Serpent",
        "abrv": "Ser",
        "total": 10,
        "power": 18,
        "skill": 2,
        "requires": [{ "behemoth": 2 }],
        "native": ["jungle"],
        "fly": false,
        "range": false
    },
    "titan": {
        "name": "Titan",
        "abrv": "Ttn",
        "total": 6,
        "power": 6,
        "skill": 4,
        "requires": [],
        "native": [],
        "fly": false,
        "range": false
    },
    "troll": {
        "name": "Troll",
        "abrv": "Tro",
        "total": 28,
        "power": 8,
        "skill": 2,
        "requires": [{ "ogre": 2 }],
        "native": ["marsh", "swamp"],
        "fly": false,
        "range": false
    },
    "unicorn": {
        "name": "Unicorn",
        "abrv": "Uni",
        "total": 12,
        "power": 6,
        "skill": 4,
        "requires": [{ "warbear": 2 }, { "minotaur": 2 }],
        "native": ["woods", "hills"],
        "fly": false,
        "range": false
    },
    "warbear": {
        "name": "Warbear",
        "abrv": "Wbe",
        "total": 21,
        "power": 6,
        "skill": 3,
        "requires": [{ "centaur": 2 }],
        "native": ["tundra", "woods"],
        "fly": false,
        "range": false
    },
    "warlock": {
        "name": "Warlock",
        "abrv": "Wlo",
        "total": 6,
        "power": 5,
        "skill": 4,
        "requires": [{ "titan": 1 }],
        "native": ["tower"],
        "fly": false,
        "range": true
    },
    "wyvern": {
        "name": "Wyvern",
        "abrv": "Wyv",
        "total": 18,
        "power": 7,
        "skill": 3,
        "requires": [{ "troll": 3 }],
        "native": ["swamp"],
        "fly": true,
        "range": true
    }
}
