export default {
    code: "H",
    name: "Hills",
    natives: [ "minotaur", "ogre", "unicorn" ],
    hazards: {
        B1: ["slope","slope","slope",null,null,null],
        B3: ["slope","slope","slope","slope","slope","slope"],
        D2: ["slope","slope","slope","slope","slope","slope"],
        D6: [null,null,"slope","slope","slope",null],
        E3: ["slope","slope","slope","slope","slope","slope"],
    },
    battlemap: {
        A1: 0,
        A2: 0,
        A3: 0,
        B1: 1,
        B2: 0,
        B3: 1,
        B4: 0,
        C1: 0,
        C2: 'tree',
        C3: 0,
        C4: 'tree',
        C5: 0,
        D1: 0,
        D2: 1,
        D3: 0,
        D4: 0,
        D5: 0,
        D6: 1,
        E1: 0,
        E2: 0,
        E3: 1,
        E4: 0,
        E5: 0,
        F1: 0,
        F2: 'tree',
        F3: 0,
        F4: 0
    }
};
