export default {
    code: 'J',
    name: 'Jungle',
    natives: ['minotaur', 'ogre', 'unicorn'],
    battlemap: {
        A1: 0,
        A2: 'bramble',
        A3: 0,
        B1: 0,
        B2: 0,
        B3: 0,
        B4: 'tree',
        C1: 'bramble',
        C2: 0,
        C3: 'bramble',
        C4: 0,
        C5: 'bramble',
        D1: 0,
        D2: 0,
        D3: 'tree',
        D4: 'bramble',
        D5: 0,
        D6: 0,
        E1: 0,
        E2: 'bramble',
        E3: 0,
        E4: 0,
        E5: 0,
        F1: 0,
        F2: 0,
        F3: 'tree',
        F4: 'bramble'
    }
};
