export default {
    code: 'm',
    name: 'Mountains',
    hazards: {
        A1: ["slope",null,null,null,null,null],
        B1: ["slope","cliff","slope",null,null,"slope"],
        B2: ["slope","slope","slope",null,null,"slope"],
        B4: [null,null,null,"slope","slope", "slope"],
        B4: [null,null,null,"slope","slope",null],
        C1: ["slope","slope","slope",null,null],
        C4: [null,null,null,null, "slope", null],
        C5: [null, null, "slope","slope","slope",null],

        D3: [null,null,"slope","slope","slope","slope"],
        D4: ["slope","slope","slope","cliff","slope","slope"],
        D6: [null,null,"slope","slope",null,null],
        E3: [null,null,null, "slope",null,null],
        F1: [null,null,null,null,"slope","slope"],
        F2: ["slope",null,null,"slope", "cliff","slope"],
        F4: [null,null,null,"slope","slope","slope"],
    },
    battlemap: {
        A1: 1,
        A2: 0,
        A3: 0,
        B1: 2,
        B2: 1,
        B3: 0,
        B4: 1,
        C1: 2,
        C2: 0,
        C3: 0,
        C4: 1,
        C5: 2,
        D1: 0,
        D2: 0,
        D3: 1,
        D4: 'volcano',
        D5: 1,
        D6: 2,
        E1: 0,
        E2: 0,
        E3: 1,
        E4: 1,
        E5: 1,
        F1: 1,
        F2: 2,
        F3: 1,
        F4: 2
    }
};
