export default {
    code: 'T',
    name: 'Tower',
    natives: ['gargoyle', 'ogre', 'centaur'],
    hazards: {
        C4: ["wall",null,null,null,"wall","wall"],
        D5: ["wall","wall",null,null,null,"wall"],
        E4: ["wall","wall","wall",null,null,null],
        E3: [null,"wall","wall","wall",null,null],
        D3: [null,null,"wall","wall","wall",null],
        C3: [null,null,null,"wall","wall","wall"],
        D4: ["wall","wall","wall","wall","wall","wall"],
    },
    battlemap: {
        A1: 0,
        A2: 0,
        A3: 0,
        B1: 0,
        B2: 0,
        B3: 0,
        B4: 0,
        C1: 0,
        C2: 0,
        C3: 1,
        C4: 1,
        C5: 0,
        D1: 0,
        D2: 0,
        D3: 1,
        D4: 2,
        D5: 1,
        D6: 0,
        E1: 0,
        E2: 0,
        E3: 1,
        E4: 1,
        E5: 0,
        F1: 0,
        F2: 0,
        F3: 0,
        F4: 0
    }
};
